// const alumnos = [
//   {
//     id: 21037109,
//     boleta: 2019602194,
//     nombres: "Felix Enrique",
//     apellidos: "Vega Nolasco",
//     carrera: "Ingeniería en Informática",
//     plantel: "UPIICSA",
//   },
//   {
//     id: 12039709,
//     boleta: 2019632494,
//     nombres: "Franco Uriel",
//     apellidos: "Perez Mancilla",
//     carrera: "Ingeniería en Robotica",
//     plantel: "UPIITA",
//   },
//   {
//     id: 21037902,
//     boleta: 2019602194,
//     nombres: "Omar",
//     apellidos: "Duran Pineda",
//     carrera: "Ingeniería en Inteligencia Artificial",
//     plantel: "ESCOM",
//   },
//   {
//     id: 23709823,
//     boleta: 2019602194,
//     nombres: "Gabriel",
//     apellidos: "Longinos Juarez",
//     carrera: "Ingeniería Electrica",
//     plantel: "ESIME",
//   },
//   {
//     id: 20398923,
//     boleta: 2019602194,
//     nombres: "Marco Antonio",
//     apellidos: "Lopez Rodriguez",
//     carrera: "Ingeniería en Ciberseguridad",
//     plantel: "ESCOM",
//   },
//   {
//     id: 23979827,
//     boleta: 2019602194,
//     nombres: "Enriqueta",
//     apellidos: "Nolasco Gutierrez",
//     carrera: "Economia",
//     plantel: "ESE",
//   },
//   {
//     id: 29387923,
//     boleta: 2019602194,
//     nombres: "Alan",
//     apellidos: "Betancourt Lopez",
//     carrera: "Videojuegos",
//     plantel: "ESCOM",
//   },
//   {
//     id: 23879812,
//     boleta: 2019602194,
//     nombres: "Jose Luis",
//     apellidos: "Mendez Coria",
//     carrera: "Ingeniería Industrial",
//     plantel: "UPIICSA",
//   },
//   {
//     id: 29387912,
//     boleta: 2019602194,
//     nombres: "Pablo",
//     apellidos: "Ramirez Sanchez",
//     carrera: "Licenciatura en Farmaceutica",
//     plantel: "ESIQUIE",
//   },
// ];
